### ISSUE TITLE
Crash running "stragegy" training.

### ISSUE THREAD

**Issue by natestone** [dionhaefner/yahtzotron#5]
The training system crashes when transitioning to the "strategy" portion of the training.  The pickle files seem to be fully created from the previous steps, but the strategy portion does not run.

```
Starting Strategy
  0%|                                                                           | 0/10000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/nate/.pyenv/versions/3.9.4/bin/yatzaitron", line 33, in <module>
    sys.exit(load_entry_point('yatzaitron==0.1.dev3+g43f76df.d20241210', 'console_scripts', 'yatzaitron')())
  File "/home/nate/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/nate/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/nate/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nate/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nate/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/nate/.pyenv/versions/3.9.4/lib/python3.9/site-packages/yatzaitron/cli.py", line 76, in train
    yzt = train_strategy(yzt, num_epochs=10_000, num_rolls=yzt._ruleset.num_rolls)
  File "/home/nate/.pyenv/versions/3.9.4/lib/python3.9/site-packages/yatzaitron/training.py", line 292, in train_strategy
    loss = float(loss_fn(weights, observations, actions))
  File "/home/nate/.pyenv/versions/3.9.4/lib/python3.9/site-packages/jax/_src/array.py", line 263, in __float__
    core.check_scalar_conversion(self)
  File "/home/nate/.pyenv/versions/3.9.4/lib/python3.9/site-packages/jax/_src/core.py", line 640, in check_scalar_conversion
    raise TypeError("Only scalar arrays can be converted to Python scalars; "
TypeError: Only scalar arrays can be converted to Python scalars; got arr.ndim=1
```

I'll be looking into it as I play with the code, but haven't had a chance to yet.

Thanks!

**Comment by dionhaefner** [comment]
Thanks, fixed on master.
